### PR TITLE
Exports APIs for core process.

### PR DESCRIPTION
**Pull request by zzzze**
Allow core process accesses the APIs of clipboard.

### CODE REVIEW

**Comment by HuakunShen** [comment]
@zzzze Hi, thank you for the PR. May I ask what does the PR do in more details? 

I am not very familiar with the Tauri toolcain. Why do we need this? What does "Allow core process accesses the APIs of clipboard." mean? Is there a documentation or example I can refer to? 

Thanks

**Comment by HuakunShen** [comment]
> Allow core process accesses the APIs of clipboard.
@zzzze Hi, thank you for the PR. May I ask what does the PR do in more details? 

I am not very familiar with the Tauri toolcain. Why do we need this? What does "Allow core process accesses the APIs of clipboard." mean? Is there a documentation or example I can refer to? 

Thanks

**Comment by zzzze** [comment]
In Tauri, the core process written in Rust is the backend of the app. The APIs exported by `[tauri::command]` can only be invoked in the frontend. So this PR exports the APIs to Rust. I added a usecase in README already.

**Comment by HuakunShen** [comment]
> In Tauri, the core process written in Rust is the backend of the app. The APIs exported by `[tauri::command]` can only be invoked in the frontend. So this PR exports the APIs to Rust. I added a usecase in README already.

I see, thanks for the explanation.

**Pull request merged**
